# Generated by Django 6.1.1 on 2026-09-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_regiao', models.CharField(max_length=100)),
                ('ofertado_pelo_sistema', models.BooleanField(default=False)),
                ('municipios_relacionados', models.ManyToManyField(blank=True, to='management.municipio')),
            ],
        ),
    ]
