# Generated by Django 6.1.1 on 2026-09-18 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='nome_da_regiao',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='municipio',
            name='codigo_ibge',
            field=models.CharField(default=2502300, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
