# Generated by Django 6.1.1 on 2026-09-25 02:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_nome_da_regiao_municipio_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('identification_photo', models.ImageField(blank=True, null=True, upload_to='bus/')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='management.municipio')),
            ],
        ),
    ]
