# Generated by Django 6.1.1 on 2026-09-29 01:31

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_bus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='license_plate',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='A placa deve estar no padrão brasileiro antigo (AAA-1234) ou Mercosul (AAA1A23).', regex='^[A-Z]{3}-?[0-9][A-Z0-9][0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipio', to=settings.AUTH_USER_MODEL),
        ),
    ]
