# Generated by Django 6.1.1 on 2026-10-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_busstop_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
