# Generated by Django 6.1.1 on 2026-10-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_busstop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
