# Generated by Django 6.1.1 on 2026-09-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_anamento', 'Em andamento'), ('concluida', 'Concluida')], max_length=20)),
                ('momento_iniciado', models.DateField(blank=True, null=True)),
                ('momento_finalizado', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
