# Generated by Django 6.1.1 on 2026-09-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='momento_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='momento_iniciado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
