# Generated by Django 6.1.1 on 2026-09-23 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_viagem_data_alter_viagem_momento_finalizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDaViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante', models.CharField(max_length=50, unique=True)),
                ('direcao', models.CharField(choices=[('ida', 'Ida'), ('volta', 'Volta')], max_length=20)),
                ('presente', models.BooleanField(default=False)),
                ('instituicao', models.CharField(max_length=60)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.viagem', unique=True)),
            ],
        ),
    ]
