# Generated by Django 6.1.1 on 2026-09-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_usuariodaviagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodaviagem',
            name='direcao',
            field=models.CharField(choices=[('ida', 'Ida'), ('volta', 'Volta'), ('ida e volta', 'Ida e Volta')], max_length=20),
        ),
    ]
