# Generated by Django 6.1.1 on 2026-09-23 19:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_studentprofile_period'),
        ('operation', '0004_alter_usuariodaviagem_direcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodaviagem',
            name='horario_saida_aluno',
            field=models.TimeField(default=datetime.datetime(2026, 9, 23, 19, 22, 52, 506160, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariodaviagem',
            name='moderador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuariodaviagem',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='authentication.studentprofile'),
        ),
        migrations.AlterField(
            model_name='usuariodaviagem',
            name='instituicao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuariodaviagem',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='operation.viagem'),
        ),
        migrations.AddConstraint(
            model_name='usuariodaviagem',
            constraint=models.UniqueConstraint(fields=('estudante', 'viagem'), name='unique_estudante_viagem'),
        ),
    ]
