# Generated by Django 6.1.1 on 2026-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_usuariodaviagem_horario_saida_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodaviagem',
            name='moderador',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
