# Generated by Django 6.1.1 on 2026-09-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_studentprofile_period'),
        ('operation', '0006_alter_usuariodaviagem_moderador'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuariodaviagem',
            constraint=models.UniqueConstraint(condition=models.Q(('moderador', True)), fields=('viagem',), name='unique_moderador_por_viagem', violation_error_message='Essa viagem já possui um moderador definido.'),
        ),
        migrations.AlterConstraint(
            model_name='usuariodaviagem',
            name='unique_estudante_viagem',
            constraint=models.UniqueConstraint(fields=('estudante', 'viagem'), name='unique_estudante_viagem', violation_error_message='Esse aluno já está registrado nessa viagem.'),
        ),
    ]
