# Generated by Django 6.1.1 on 2026-09-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_usuariodaviagem_unique_moderador_por_viagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodaviagem',
            name='moderador',
            field=models.BooleanField(default=False),
        ),
    ]
