# Generated by Django 6.1.1 on 2026-10-02 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_alter_usuariodaviagem_moderador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('dias_funcionamento', models.CharField(default='Seg - Sex', max_length=50)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='viagem',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.linha'),
        ),
    ]
