# Generated by Django 6.1.1 on 2026-10-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_linha_alter_viagem_linha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='linha',
            field=models.CharField(max_length=50),
        ),
    ]
