# Generated by Django 6.1.1 on 2026-10-02 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_alter_viagem_linha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.linha'),
        ),
    ]
