# Generated by Django 6.1.1 on 2026-09-24 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRouteDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StopMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_stop', models.CharField(max_length=100)),
                ('end_stop', models.CharField(max_length=100)),
                ('distance', models.DecimalField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('order', models.PositiveIntegerField()),
                ('last_route_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_metrics', to='metrics.lastrouteday')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentsUsingBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=50)),
                ('day', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('user', 'route', 'day'), name='unique_student_route_day')],
            },
        ),
    ]
