# Generated by Django 6.1.1 on 2026-09-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastrouteday',
            name='is_concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='stopmetrics',
            constraint=models.UniqueConstraint(fields=('last_route_day', 'order'), name='unique_order_per_route_day'),
        ),
    ]
