# Generated by Django 6.1.1 on 2026-09-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_lastrouteday_is_concluded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastrouteday',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
