# Generated by Django 6.1.1 on 2026-09-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_lastrouteday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopmetrics',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
