# Generated by Django 6.1.1 on 2026-09-25 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_stopmetrics_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastrouteday',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='lastrouteday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='lastrouteday',
            constraint=models.UniqueConstraint(fields=('line', 'route', 'date'), name='unique_line_route_per_day'),
        ),
    ]
