# Generated by Django 6.1.1 on 2026-09-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_alter_lastrouteday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastrouteday',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
