# Generated by Django 6.1.1 on 2026-09-25 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_alter_lastrouteday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastrouteday',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
