# Generated by Django 6.1.1 on 2026-09-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_alter_lastrouteday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastrouteday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
