# Generated by Django 6.1.1 on 2026-10-08 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_alter_lastrouteday_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lastrouteday',
            name='unique_line_route_per_day',
        ),
        migrations.RemoveConstraint(
            model_name='studentsusingbus',
            name='unique_student_route_day',
        ),
        migrations.RemoveField(
            model_name='stopmetrics',
            name='end_stop',
        ),
        migrations.RemoveField(
            model_name='stopmetrics',
            name='start_stop',
        ),
        migrations.AddField(
            model_name='lastrouteday',
            name='line_id',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lastrouteday',
            name='route_id',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='stopmetrics',
            name='end_stop_id',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='stopmetrics',
            name='start_stop_id',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='studentsusingbus',
            name='route_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='stopmetrics',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='lastrouteday',
            constraint=models.UniqueConstraint(fields=('line_id', 'route_id', 'date'), name='unique_line_route_per_day'),
        ),
        migrations.AddConstraint(
            model_name='studentsusingbus',
            constraint=models.UniqueConstraint(fields=('user', 'route_id', 'day'), name='unique_student_route_day'),
        ),
        migrations.RemoveField(
            model_name='lastrouteday',
            name='line',
        ),
        migrations.RemoveField(
            model_name='lastrouteday',
            name='route',
        ),
        migrations.RemoveField(
            model_name='studentsusingbus',
            name='route',
        ),
    ]
