# Generated by Django 6.1.1 on 2026-10-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_remove_lastrouteday_unique_line_route_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastrouteday',
            name='line_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lastrouteday',
            name='route_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stopmetrics',
            name='end_stop_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stopmetrics',
            name='start_stop_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsusingbus',
            name='route_id',
            field=models.IntegerField(),
        ),
    ]
