# Generated by Django 6.1.1 on 2026-09-24 20:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def birth_date_para_perfis(apps, schema_editor):
    """Move ``User.birth_date`` para os perfis antes de remover o campo.

    O ``birth_date`` hoje e um placeholder que mora nos perfis (sera
    devolvido ao ``User`` quando o modulo ``management.City`` for
    liberado), entao os dados ja cadastrados precisam ser copiados.
    """
    User = apps.get_model("authentication", "User")
    StudentProfile = apps.get_model("authentication", "StudentProfile")
    PersonelProfile = apps.get_model("authentication", "PersonelProfile")

    for perfil in StudentProfile.objects.select_related("user"):
        if perfil.birth_date is None and perfil.user.birth_date is not None:
            perfil.birth_date = perfil.user.birth_date
            perfil.save(update_fields=["birth_date"])

    usuarios_sem_perfil_de_aluno = User.objects.exclude(
        birth_date=None
    ).filter(student_profile__isnull=True)

    for usuario in usuarios_sem_perfil_de_aluno:
        PersonelProfile.objects.get_or_create(
            user=usuario, defaults={"birth_date": usuario.birth_date}
        )


def birth_date_de_volta_para_o_user(apps, schema_editor):
    """Reverte a copia: devolve ``birth_date`` do perfil para o ``User``."""
    User = apps.get_model("authentication", "User")
    StudentProfile = apps.get_model("authentication", "StudentProfile")
    PersonelProfile = apps.get_model("authentication", "PersonelProfile")

    datas = {
        perfil.user_id: perfil.birth_date
        for perfil in StudentProfile.objects.exclude(birth_date=None)
    }
    for perfil in PersonelProfile.objects.exclude(birth_date=None):
        datas.setdefault(perfil.user_id, perfil.birth_date)

    for usuario_id, birth_date in datas.items():
        User.objects.filter(pk=usuario_id).update(birth_date=birth_date)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='period',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.CreateModel(
            name='PersonelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personel_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            birth_date_para_perfis,
            birth_date_de_volta_para_o_user,
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
