# Generated by Django 6.1.1 on 2026-09-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_studentprofile_period'),
        ('authentication', '0004_remove_user_birth_date_studentprofile_birth_date_and_more'),
    ]

    operations = [
    ]
