# Generated by Django 6.1.1 on 2026-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20260925_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personelprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='personelprofile',
            name='city_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
