# Generated by Django 6.1.1 on 2026-09-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20260924_2310'),
        ('management', '0003_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.municipio'),
        ),
    ]
