# Generated by Django 6.1.1 on 2026-10-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_personelprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='city_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
